name: Deploy The Big Red Button

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Push The Big Red Button 🔴
        run: echo "The Big Red Button has been pressed! Deployment started."